version: '3.9'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE:"true"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - kafka
      - zookeeper
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER_URL=kafka:9092
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_EMAIL-${MAILGUN_EMAIL}
      - QUEUE_NAME=${QUEUE_NAME}
      - TOPIC_NAME=${TOPIC_NAME}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - ONESIGNAL_API_KEY=${ONESIGNAL_API_KEY}
      - ONESIGNAL_APP_ID=${ONESIGNAL_APP_ID}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - REDIS_TIME_LIMIT=${REDIS_TIME_LIMIT}
      - ENV=${ENV}
      - PROJECT_ID=${PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
